export const PAYMENT_CARD_NUMBER_LENGTH = 16;
export const PAYMENT_CARD_NUMBER_MAX_INPUT = 19; // 16 digits + 3 spaces
export const PAYMENT_CVV_MAX_LENGTH = 4;
export const PAYMENT_EXPIRY_DIGITS = 4;
export const PAYMENT_EXPIRY_MAX_LENGTH = 5;
export const PAYMENT_SUCCESS_REDIRECT_DELAY = 2000;
export const PAYMENT_EXPIRY_CENTURY_BASE = 2000;

export const PAYMENT_FIELD_BORDER_RADIUS = 10;
export const PAYMENT_ERROR_BORDER_RADIUS = 8;
export const PAYMENT_HEADER_PADDING_TOP = 5;
export const PAYMENT_SUCCESS_ICON_SIZE = 56;
export const PAYMENT_SUCCESS_ICON_SIZE_MD = 72;
export const PAYMENT_CARD_ICON_WIDTH = 52;
export const PAYMENT_CARD_ICON_HEIGHT = 34;
export const PAYMENT_CARD_ICON_WIDTH_MD = 66;
export const PAYMENT_CARD_ICON_HEIGHT_MD = 42;
export const PAYMENT_CARD_ICON_BORDER_RADIUS = 6;
export const PAYMENT_CARD_ICON_BORDER_ALPHA = 0.15;
export const PAYMENT_CARD_ICON_BG_ALPHA_DARK_ACTIVE = 0.1;
export const PAYMENT_CARD_ICON_BG_ALPHA_DARK_INACTIVE = 0.04;
export const PAYMENT_CARD_ICON_BG_ALPHA_LIGHT_INACTIVE = 0.7;
export const PAYMENT_BUTTON_MARGIN_TOP = 7;
export const PAYMENT_BUTTON_MARGIN_TOP_MD = 10;
export const PAYMENT_BUTTON_DISABLED_OPACITY = 0.6;
export const PAYMENT_CARD_INACTIVE_OPACITY = 0.45;

export const CARD_NUMBER_REGEX = /^\d{16}$/;
export const EXPIRY_REGEX = /^(0[1-9]|1[0-2])\/\d{2}$/;
export const CVV_REGEX = /^\d{3,4}$/;

export const VISA_PREFIX_REGEX = /^4/;
export const MASTERCARD_PREFIX_REGEX = /^5[1-5]|^2[2-7]/;

export const VISA_ICON_WIDTH = 38;
export const VISA_ICON_HEIGHT = 13;
export const VISA_ICON_VIEWBOX = "0 0 38 13";
export const VISA_ICON_LABEL = "Visa";
export const MASTERCARD_ICON_WIDTH = 36;
export const MASTERCARD_ICON_HEIGHT = 24;
export const MASTERCARD_ICON_VIEWBOX = "0 0 36 24";
export const MASTERCARD_ICON_LABEL = "Mastercard";
